const log = require("./index.js");
log.config.CLEAR_TIMEOUT = 2000;
log.clear().then(() => {
  log.header("hello header");
  log.subHeader2("hello world");
  log.subHeader1("and the last row");
  log.setColor(log.COLORS.FgLtMagenta, log.COLORS.BgLtGreen);
  log.line();
  log.log("hello world");
  log.setBgColor(log.COLORS.BgDefault);
  log.line();
  log.log("hello world", 1, 2, 3);
  log.footer("This is the foooter");
  log.comment("this is a comment");
  log.reset();
  log.config.HEADER_BORDER_COLOR = log.COLORS.FgLtRed;
  log.config.HEADER_TEXT_COLOR = log.COLORS.FgLtYellow;
  log.header("new colors");
  log.footer("bye bye");
});
